import {
  Box,
  Card,
  Grid,
  IconButton,
  InputAdornment,
  InputBase,
  OutlinedInput,
  Typography,
} from "@mui/material";
// import Document from "next/document";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import SButton from "../../salmComponenets/Button/1.01";
import SearchIcon from "@mui/icons-material/Search";
import HotelIcon from "@mui/icons-material/Hotel";
import LocalActivityIcon from "@mui/icons-material/LocalActivity";
import ApartmentIcon from "@mui/icons-material/Apartment";
import VolunteerActivismIcon from "@mui/icons-material/VolunteerActivism";
import AccountBalanceWalletIcon from "@mui/icons-material/AccountBalanceWallet";
import LocationCityIcon from "@mui/icons-material/LocationCity";
import LandscapeIcon from "@mui/icons-material/Landscape";
import LocalDiningIcon from "@mui/icons-material/LocalDining";
import GroupsIcon from "@mui/icons-material/Groups";
import styles from "../../styles/Home.module.css";

import React, { Component } from "react";

export default class Mitra extends Component {
  constructor(props) {
    super(props);
    this.state = {
      nano: null,
    };
  }
  render() {
    return (
      <div>
        <Head>
          <title>DGMall Syariah Help Center</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/LogoDgmall.png" />
        </Head>

        <div>
          <div>
            <Box sx={{ display: { xs: "none", sm: "block" } }}>
              <div style={{ marginTop: "20px", marginLeft: "70px" }}>
                <Image
                  src="/logoDgmall.png"
                  width={60}
                  height={60}
                  alt="logo"
                />
              </div>
            </Box>
            <Box sx={{ display: { xs: "block", sm: "none" } }}>
              <div style={{ marginTop: "10px", marginLeft: "10px" }}>
                <Image
                  src="/logoDgmall.png"
                  width={40}
                  height={40}
                  alt="logo"
                />
              </div>
            </Box>

            <Box sx={{ display: { xs: "none", sm: "block" } }}>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-around",
                  alignItems: "center",
                }}
              >
                <div>
                  <h1>
                    Assalamualaikum,
                    <br />
                    Selamat Datang Di Help Center DGMall Syariah,
                    <br />
                    Ada yang Bisa Kami Bantu ?
                  </h1>
                  <div
                    style={{
                      display: "flex",
                      background: "grexy",
                      borderRadius: "50px",
                    }}
                  >
                    <OutlinedInput
                      id="outlined-adornment-weight"
                      fullWidth
                      // value={values.weight}
                      // onChange={handleChange("weight")}
                      endAdornment={
                        <InputAdornment position="end">
                          <SearchIcon />
                        </InputAdornment>
                      }
                      aria-describedby="outlined-weight-helper-text"
                      inputProps={{
                        "aria-label": "weight",
                      }}
                    />
                  </div>
                </div>
                <div>
                  <Image src="/mitra.gif" width={500} height={500} alt="logo" />
                </div>
              </div>
            </Box>

            <Box sx={{ display: { xs: "block", sm: "none" } }}>
              <div
                style={{
                  display: "inline-list-item",
                  justifyContent: "space-around",
                  textAlign: "center",
                  alignItems: "center",
                }}
              >
                <div>
                  <div>
                    <Image
                      src="/mitra.gif"
                      width={250}
                      height={250}
                      alt="logo"
                    />
                  </div>
                  <div
                    style={{
                      padding: "15px",
                    }}
                  >
                    <h3>
                      <strong>
                        Assalamualaikum,
                        <br />
                        Selamat Datang Di Help Center DGMall Syariah,
                        <br />
                        Ada yang Bisa Kami Bantu ?
                      </strong>
                    </h3>
                  </div>
                  <div
                    style={{
                      display: "inline-list-item",
                      background: "grexy",
                      borderRadius: "50px",
                      paddingBottom: "50px",
                    }}
                  >
                    <OutlinedInput
                      id="outlined-adornment-weight"
                      sx={{ width: "300px", height: "30px" }}
                      // value={values.weight}
                      // onChange={handleChange("weight")}
                      endAdornment={
                        <InputAdornment position="end">
                          <SearchIcon />
                        </InputAdornment>
                      }
                      aria-describedby="outlined-weight-helper-text"
                      inputProps={{
                        "aria-label": "weight",
                      }}
                    />
                  </div>
                </div>
              </div>
            </Box>

            <Box sx={{ display: { xs: "none", sm: "block" } }}>
              <div
                style={{
                  alignItems: "center",
                  borderRadius: "50px",
                  display: "flex",
                  justifyContent: "center",
                }}
              >
                <div
                  className={styles.btn}
                  style={{
                    marginlef: "25px",
                    marginRight: "25px",
                  }}
                >
                  <Link href="/pembeli">
                    <SButton
                      type="button"
                      fontSize="15px"
                      radius="50px"
                      cursor="pointer"
                      bgcolor="grey"
                      color="white"
                      title="Pembeli"
                      padding="10px"
                      border="none"
                      paddingLeft="100px"
                      paddingRight="100px"
                    />
                  </Link>
                </div>

                <div
                  className={styles.btn}
                  style={{
                    marginlef: "25px",
                    marginRight: "25px",
                  }}
                >
                  <Link href="./penjual">
                    <SButton
                      type="button"
                      fontSize="15px"
                      radius="50px"
                      cursor="pointer"
                      bgcolor="grey"
                      color="white"
                      title="Penjual"
                      padding="10px"
                      border="none"
                      paddingLeft="100px"
                      paddingRight="100px"
                    />
                  </Link>
                </div>

                <div
                  className={styles.btn}
                  style={{
                    marginlef: "25px",
                    marginRight: "25px",
                  }}
                >
                  <Link href="./mitra">
                    <SButton
                      type="button"
                      fontSize="15px"
                      radius="50px"
                      cursor="pointer"
                      bgcolor="#10856c"
                      color="white"
                      title="Mitra"
                      padding="10px"
                      border="none"
                      paddingLeft="100px"
                      paddingRight="100px"
                    />
                  </Link>
                </div>
              </div>
            </Box>

            <Box sx={{ display: { xs: "block", sm: "none" } }}>
              <div
                style={{
                  alignItems: "center",
                  borderRadius: "50px",
                  display: "inline-list-item",
                  justifyContent: "center",
                }}
              >
                <div
                  style={{
                    textAlign: "center",
                    alignItems: "center",
                    marginleft: "25px",
                    marginRight: "25px",
                  }}
                >
                  <Link href="/pembeli">
                    <SButton
                      type="button"
                      fontSize="15px"
                      radius="50px"
                      cursor="pointer"
                      bgcolor="grey"
                      color="white"
                      margin="10px"
                      title="Pembeli"
                      padding="10px"
                      border="none"
                      paddingLeft="97px"
                      paddingRight="97px"
                    />
                  </Link>
                </div>

                <div
                  style={{
                    textAlign: "center",
                    alignItems: "center",
                    marginlef: "25px",
                    marginRight: "25px",
                  }}
                >
                  <Link href="./penjual">
                    <SButton
                      type="button"
                      fontSize="15px"
                      radius="50px"
                      cursor="pointer"
                      bgcolor="grey"
                      color="white"
                      margin="10px"
                      title="Penjual"
                      padding="10px"
                      border="none"
                      paddingLeft="100px"
                      paddingRight="100px"
                    />
                  </Link>
                </div>

                <div
                  style={{
                    textAlign: "center",
                    alignItems: "center",
                    marginlef: "25px",
                    marginRight: "25px",
                  }}
                >
                  <Link href="./mitra">
                    <SButton
                      type="button"
                      fontSize="15px"
                      radius="50px"
                      cursor="pointer"
                      bgcolor="#10856c"
                      color="white"
                      margin="10px"
                      title="Mitra"
                      padding="10px"
                      border="none"
                      paddingLeft="107px"
                      paddingRight="107px"
                    />
                  </Link>
                </div>
              </div>
            </Box>

            <Box sx={{ display: { xs: "none", sm: "block" } }}>
              <div
                style={{
                  paddingLeft: 50,
                  paddingRight: 50,
                  border: "#10856c solid 1px",
                  borderRadius: "5px",
                  marginTop: "50px",
                  marginLeft: 30,
                  marginRight: 30,
                }}
              >
                <div>
                  <h2>Kategori Mitra</h2>
                </div>
                <div
                  style={{
                    // alignItems: "center",
                    justifyContent: "space-between",
                    paddingBottom: "25px",
                    display: "flex",
                  }}
                >
                  <Link href="/">
                    <div
                      className={styles.btn}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        background: "#10856c",
                        borderRadius: "5px",
                        border: "1px solid ",
                        borderColor: "#10856c",
                        paddingLeft: 20,
                        width: 280,
                        height: 65,
                      }}
                    >
                      <div
                        style={{
                          color: "#fefefe",
                        }}
                      >
                        <HotelIcon fontSize="large" />
                      </div>
                      <div
                        style={{
                          textAlign: "center",
                          color: "white",
                          paddingLeft: 20,
                        }}
                      >
                        <h4>Staycation</h4>
                      </div>
                    </div>
                  </Link>
                  <Link href="/">
                    <div
                      className={styles.btn}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        background: "#10856c",
                        borderRadius: "5px",
                        border: "1px solid ",
                        borderColor: "#10856c",
                        paddingLeft: 20,
                        width: 280,
                        height: 65,
                      }}
                    >
                      <div
                        style={{
                          color: "#fefefe",
                        }}
                      >
                        <LocalActivityIcon fontSize="large" />
                      </div>
                      <div
                        style={{
                          textAlign: "left",
                          color: "white",
                          paddingLeft: 20,
                        }}
                      >
                        <h4>Event</h4>
                      </div>
                    </div>
                  </Link>
                  <Link href="./madrasah">
                    <div
                      className={styles.btn}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        background: "#10856c",
                        borderRadius: "5px",
                        border: "1px solid ",
                        borderColor: "#10856c",
                        paddingLeft: 20,
                        width: 280,
                        height: 65,
                      }}
                    >
                      <div
                        style={{
                          color: "#fefefe",
                        }}
                      >
                        <AccountBalanceWalletIcon fontSize="large" />
                      </div>
                      <div
                        style={{
                          textAlign: "center",
                          color: "white",
                          paddingLeft: 20,
                        }}
                      >
                        <h4>Dompet Madrasah</h4>
                      </div>
                    </div>
                  </Link>
                  <Link href="">
                    <div
                      className={styles.btn}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        background: "#10856c",
                        borderRadius: "5px",
                        border: "1px solid ",
                        borderColor: "#10856c",
                        paddingLeft: 20,
                        width: 280,
                        height: 65,
                      }}
                    >
                      <div
                        style={{
                          color: "#fefefe",
                        }}
                      >
                        <VolunteerActivismIcon fontSize="large" />
                      </div>
                      <div
                        style={{
                          textAlign: "left",
                          color: "white",
                          paddingLeft: 20,
                        }}
                      >
                        <h4>Donasi</h4>
                      </div>
                    </div>
                  </Link>
                </div>

                {/* TENGAH*/}
                {/* <div
                  style={{
                    // alignItems: "center",
                    justifyContent: "space-between",
                    paddingBottom: "25px",
                    display: "flex",
                  }}
                >
                  <Link href="./madrasah">
                    <div
                      style={{
                        display: "flex",
                        alignItems: "center",
                        background: "#10856c",
                        borderRadius: "5px",
                        border: "1px solid ",
                        borderColor: "#10856c",
                        paddingLeft: 20,
                        width: 280,
                        height: 65,
                      }}
                    >
                      <div
                        style={{
                          color: "#fefefe",
                        }}
                      >
                        <AccountBalanceWalletIcon fontSize="large" />
                      </div>
                      <div
                        style={{
                          textAlign: "center",
                          color: "white",
                          paddingLeft: 20,
                        }}
                      >
                        <h4>Dompet Madrasah</h4>
                      </div>
                    </div>
                  </Link>
                  <Link href="/">
                    <div
                      style={{
                        display: "flex",
                        alignItems: "center",
                        background: "#10856c",
                        borderRadius: "5px",
                        border: "1px solid ",
                        borderColor: "#10856c",
                        paddingLeft: 20,
                        width: 280,
                        height: 65,
                      }}
                    >
                      <div
                        style={{
                          color: "#fefefe",
                        }}
                      >
                        <LocationCityIcon fontSize="large" />
                      </div>
                      <div
                        style={{
                          textAlign: "left",
                          color: "white",
                          paddingLeft: 20,
                        }}
                      >
                        <h4>Hotel</h4>
                      </div>
                    </div>
                  </Link>
                  <Link href="/">
                    <div
                      style={{
                        display: "flex",
                        alignItems: "center",
                        background: "#10856c",
                        borderRadius: "5px",
                        border: "1px solid ",
                        borderColor: "#10856c",
                        paddingLeft: 20,
                        width: 280,
                        height: 65,
                      }}
                    >
                      <div
                        style={{
                          color: "#fefefe",
                        }}
                      >
                        <LandscapeIcon fontSize="large" />
                      </div>
                      <div
                        style={{
                          textAlign: "left",
                          color: "white",
                          paddingLeft: 20,
                        }}
                      >
                        <h4>Wisata</h4>
                      </div>
                    </div>
                  </Link>
                  <Link href="/">
                    <div
                      style={{
                        display: "flex",
                        alignItems: "center",
                        background: "#10856c",
                        borderRadius: "5px",
                        border: "1px solid ",
                        borderColor: "#10856c",
                        paddingLeft: 20,
                        width: 280,
                        height: 65,
                      }}
                    >
                      <div
                        style={{
                          color: "#fefefe",
                        }}
                      >
                        <LocalDiningIcon fontSize="large" />
                      </div>
                      <div
                        style={{
                          textAlign: "left",
                          color: "white",
                          paddingLeft: 20,
                        }}
                      >
                        <h4>Kuliner</h4>
                      </div>
                    </div>
                  </Link>
                </div> */}

                {/* BAWAH*/}
                {/* <div
                  style={{
                    // alignItems: "center",
                    justifyContent: "center",
                    paddingBottom: "25px",
                    display: "flex",
                  }}
                >
                  <Link href="/">
                    <div
                      style={{
                        display: "flex",
                        alignItems: "center",
                        background: "#10856c",
                        borderRadius: "5px",
                        border: "1px solid ",
                        borderColor: "#10856c",
                        paddingLeft: 20,
                        width: 280,
                        height: 65,
                      }}
                    >
                      <div
                        style={{
                          color: "#fefefe",
                        }}
                      >
                        <GroupsIcon fontSize="large" />
                      </div>
                      <div
                        style={{
                          textAlign: "center",
                          color: "white",
                          paddingLeft: 20,
                        }}
                      >
                        <h4>Warga</h4>
                      </div>
                    </div>
                  </Link> 
                </div> */}
              </div>
            </Box>

            <Box sx={{ display: { xs: "block", sm: "none" } }}>
              <div
                style={{
                  paddingLeft: 25,
                  paddingRight: 25,
                  alignItems: "center",
                  paddingBottom: 30,
                  border: "#10856c solid 1px",
                  borderRadius: "5px",
                  marginTop: "50px",
                  marginLeft: 30,
                  marginRight: 30,
                }}
              >
                <div>
                  <h2>Kategori Mitra</h2>
                </div>
                <Grid container spacing={1}>
                  <Grid item xs={4}>
                    <Link href="./">
                      <Card
                        sx={{
                          maxWidth: 60,
                          textAlign: "center",
                          height: 85,
                          color: "white",
                          backgroundColor: "#10856c",
                        }}
                      >
                        <HotelIcon fontSize="large" />
                        <Typography
                          align="center"
                          display="block"
                          sx={{ fontSize: "10px" }}
                        >
                          Staycation
                        </Typography>
                      </Card>
                    </Link>
                  </Grid>

                  <Grid item xs={4}>
                    <Link href="./">
                      <Card
                        sx={{
                          maxWidth: 60,
                          textAlign: "center",
                          height: 85,
                          color: "white",
                          backgroundColor: "#10856c",
                        }}
                      >
                        <LocalActivityIcon fontSize="large" />
                        <Typography
                          align="center"
                          display="block"
                          sx={{ fontSize: "10px" }}
                        >
                          Event
                        </Typography>
                      </Card>
                    </Link>
                  </Grid>

                  <Grid item xs={4}>
                    <Link href="./">
                      <Card
                        sx={{
                          maxWidth: 60,
                          textAlign: "center",
                          height: 85,
                          color: "white",
                          backgroundColor: "#10856c",
                        }}
                      >
                        <AccountBalanceWalletIcon fontSize="large" />
                        <Typography
                          align="center"
                          display="block"
                          sx={{ fontSize: "10px" }}
                        >
                          Dompet Madrasah
                        </Typography>
                      </Card>
                    </Link>
                  </Grid>

                  <Grid item xs={4}>
                    <Link href="./">
                      <Card
                        sx={{
                          maxWidth: 60,
                          textAlign: "center",
                          height: 85,
                          color: "white",
                          backgroundColor: "#10856c",
                        }}
                      >
                        <VolunteerActivismIcon fontSize="large" />
                        <Typography
                          align="center"
                          display="block"
                          sx={{ fontSize: "10px" }}
                        >
                          Donasi
                        </Typography>
                      </Card>
                    </Link>
                  </Grid>
                </Grid>
              </div>
            </Box>
          </div>
        </div>

        <div
          style={{
            alignItems: "center",
            justifyContent: "center",
            padding: "50px",
            display: "flex",
          }}
        >
          <div>
            <a
              href="https://info.dgmall.id/aboutUs"
              target="_blank"
              rel="noopener noreferrer"
            >
              {/* <h3>Powered by</h3> <span className={styles.logo}></span> */}
            </a>
          </div>

          <Box sx={{ display: { xs: "none", sm: "block" } }}>
            <div style={{ verticalAlign: "baseline" }}>
              <Image src="/logoDgmall.png" alt="Logo" width={50} height={50} />
            </div>
          </Box>
          <Box sx={{ display: { xs: "block", sm: "none" } }}>
            <div style={{ verticalAlign: "baseline" }}>
              <Image src="/logoDgmall.png" alt="Logo" width={30} height={30} />
            </div>
          </Box>
        </div>
      </div>
    );
  }
}
